spring.application.name=creator
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.envers.audit_table_suffix=_AUDIT
spring.jpa.properties.hibernate.envers.audit_schema=poomaalai_audit
spring.jpa.properties.hibernate.envers.store_data_at_delete=true
server.port=${PORT:8080}
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=WARN
logging.level.org.springframework.http=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.security.web=INFO
logging.level.org.springframework.security.authentication=INFO
logging.level.org.springframework.security.core=INFO
logging.level.org.hibernate=WARN
logging.level.com.poomaalai=INFO
# Liquibase Configuration (optional, defaults are fine)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true


# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}
# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}


# Geocoding Configuration
geocoding.enabled=${GEOCODING_ENABLED}
geocoding.provider=${GEOCODING_PROVIDER}
geocoding.api.key=${AIzaSyAv6cVi8rFXl0a62cvGP5dOvMtlP33cu6k}
geocoding.nominatim.url=${GEOCODING_NOMINATIM_URL}
geocoding.google.url=${GEOCODING_GOOGLE_URL}